[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
fs_permissions = [{ access = "read-write", path = "./"}]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

[profile.ci]
fuzz = { runs = 256  }
invariant = { runs = 256 }

[lint]
# Disable the asm-keccak256 lint - we prefer readable keccak256() calls over assembly
exclude_lints = ["asm-keccak256"]

[fmt]
int_types = "long"           # Enforces "uint256" over "uint" (Implicit in your examples)
line_length = 120
multiline_func_header = "attributes_first" 
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
bracket_spacing = false      # Matches "No spaces inside brackets: arr[i]" 
sort_imports = true          # Enforces "Strictly alphabetize imports"

[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"
polygon = "https://rpc.ankr.com/polygon"
arbitrum = "https://rpc.ankr.com/arbitrum"
optimism = "https://rpc.ankr.com/optimism"
base = "https://rpc.ankr.com/base"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
