#!/bin/bash
# =============================================================================
# Generate Makefile Variables Script
# =============================================================================
# Generates Makefile-compatible variable assignments from deployment.toml.
# This script is called by the Makefile to generate .make-deploy-vars.mk.
#
# Usage:
#   ./generate_make_vars.sh <factory>
#
# Output:
#   Makefile variable assignments to stdout (redirect to .make-deploy-vars.mk)
#
# =============================================================================

set -e  # Stop on first error

# Get the directory where this script lives
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source the shared configuration library
source "$SCRIPT_DIR/deployment_config.sh"

# Validate prerequisites
validate_prerequisites

# Get factory argument
FACTORY="$1"
validate_factory "$FACTORY"

# =============================================================================
# Generate Makefile Variables
# =============================================================================

cat <<EOF
# ==============================================================================
# Auto-generated Makefile variables from deployment.toml
# ==============================================================================
# Factory: $FACTORY
# Generated by: script/sh/lib/generate_make_vars.sh
#
# DO NOT EDIT THIS FILE DIRECTLY - it is regenerated when deployment.toml changes.
# ==============================================================================

# ------------------------------------------------------------------------------
# Addresses from deployment.toml
# ------------------------------------------------------------------------------
FACTORY_ADDRESS := $(get_factory_address "$FACTORY")
FACTORY_DEPLOYER_ADDRESS := $(get_factory_deployer "$FACTORY")

# Library addresses
LIB_ORG_POLICY_ADDRESS := $(get_lib_org_policy "$FACTORY")
LIB_ORG_ADMIN_ADDRESS := $(get_lib_org_admin "$FACTORY")
LIB_ORG_INIT_ADDRESS := $(get_lib_org_init "$FACTORY")
LIB_ORG_ACCOUNT_SIG_ADDRESS := $(get_lib_org_account_sig "$FACTORY")

# Arachnid deployer address (special case for funding - always from arachnid factory)
ARACHNID_DEPLOYER_ADDRESS := $(get_factory_deployer "arachnid")

# ------------------------------------------------------------------------------
# Library Paths (for --libraries flag)
# ------------------------------------------------------------------------------
LIB_ORG_POLICY_PATH := $LIB_ORG_POLICY_PATH
LIB_ORG_ADMIN_PATH := $LIB_ORG_ADMIN_PATH
LIB_ORG_INIT_PATH := $LIB_ORG_INIT_PATH
LIB_ORG_ACCOUNT_SIG_PATH := $LIB_ORG_ACCOUNT_SIG_PATH

# ------------------------------------------------------------------------------
# Library Linking Flags (for deploy-contracts and deploy-dependent-libs)
# ------------------------------------------------------------------------------
# Independent libraries (Policy, Admin) - used for deploy-dependent-libs
INDEPENDENT_LIBRARIES_FLAGS = \\
	--libraries \$(LIB_ORG_POLICY_PATH):\$(LIB_ORG_POLICY_ADDRESS) \\
	--libraries \$(LIB_ORG_ADMIN_PATH):\$(LIB_ORG_ADMIN_ADDRESS)

# All libraries - used for deploy-contracts
ALL_LIBRARIES_FLAGS = \\
	--libraries \$(LIB_ORG_POLICY_PATH):\$(LIB_ORG_POLICY_ADDRESS) \\
	--libraries \$(LIB_ORG_ADMIN_PATH):\$(LIB_ORG_ADMIN_ADDRESS) \\
	--libraries \$(LIB_ORG_INIT_PATH):\$(LIB_ORG_INIT_ADDRESS) \\
	--libraries \$(LIB_ORG_ACCOUNT_SIG_PATH):\$(LIB_ORG_ACCOUNT_SIG_ADDRESS)
EOF
